### ISSUE TITLE
 The target entry-point "@awesome-cordova-plugins/screen-orientation" has missing dependencies

### ISSUE THREAD

**Issue by matadantelinga** [apache/cordova-plugin-screen-orientation#90]
Hi I would like to know why when I run serve the ionic on ios simulator the error was shown as bellow

[error] Error: The target entry-point "@awesome-cordova-plugins/screen-orientation" has missing dependencies:
 - @awesome-cordova-plugins/core

    at TargetedEntryPointFinder.findEntryPoints (/Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40:23)
    at /Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
    at /Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/Applications/MAMP/htdocs/naturehub-app/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/Applications/MAMP/htdocs/naturehub-app/node_modules/@ngtools/webpack/src/ngcc_processor.js:164:16)
    at /Applications/MAMP/htdocs/naturehub-app/node_modules/@ngtools/webpack/src/ivy/host.js:128:18

previously it was work fine, but somehow after I installed this package https://www.npmjs.com/package/cupertino-pane I am getting the erro.

**Comment by breautek** [comment]
Apache doesn't maintain any @awesome-cordova-plugins packages and your issue appears to be more of a angular framework level issue.

Closing because there is no clear relevance to the apache's cordova-plugin-screen-orientation.

I would encourage you to seek assistance from the maintainers of `@awesome-cordova-plugins/screen-orientation`, who would probably be better equipped to answer questions relating to their package.
